[package]
name = "packed_booleans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.serde]
version = "1.0.183"
default_features = false
features = ["derive"]
optional = true
